backend:
  name: git-gateway
  branch: main
media_folder: "assets/photos"
public_folder: "/assets/photos"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "downloads"
        label: "Downloads Page"
        file: "_data/downloads.json"
        format: json
        fields:
          - {label: "Photo Library Link", name: "photos_link", widget: "string", required: false}
          - {label: "Marketing Suite Link", name: "marketing_link", widget: "string", required: false}
          - {label: "Catalogs Link", name: "catalogs_link", widget: "string", required: false}
      - name: "photography"
        label: "Photography Page"
        file: "_data/photography.json"
        format: json
        fields:
          - {label: "Photo Library Link", name: "photos_link", widget: "string", required: false}
